version: '3.9'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  nats:
    image: nats:alpine
    command:
      - -js
      - -sd
      - /data
    volumes:
      - nats_data:/data
    ports:
      - 4222:4222
      - 8222:8222

  mongo:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS:-password}
#      MONGO_INITDB_DATABASE: labnoc
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data:
  nats_data:

